### ISSUE TITLE
need compiler support for E5 series

### ISSUE THREAD

**Issue by bombasticbob** [XMegaForArduino/arduino#5]
xmega8e5, xmega16e5, and xmega32e5 all need compiler support.  header files from ATMel Studio are a good starting point.  The layout for the serial port control registers AND the addresses for them are different enough that you can't just use the xmega32d4 header file (example, CTRLD register which is normally assigned to zero).

gcc 4.8.2 has xmega64d4 support now (newest FreeBSD port).  Similar changes and patches can be done for the earlier compiler in the debian and ubuntu packages for the E series.  ATMel wants the E series adopted from what Rodney said at the hardware hacker's meeting.  It's a TQFP 32 and has about the same number of pins as an atmega328 (no 'p') and is lower cost, etc. from what I can tell so that is incentive enough.

**Comment by bombasticbob** [comment]
E5 support still missing in Arduino 1.8.x - may need to provide tool chains in IDE project

**Comment by bombasticbob** [comment]
downloaded windows version of 1.8.1, compiler worked for 32e5.  maybe only linux needs patching?

**Comment by syddo** [comment]
Hi any luck with this issue?

**Comment by bombasticbob** [comment]
latest arduino IDE appears to support it.  source patches are available in XMegaForArduino/patches

**Comment by bombasticbob** [comment]
Since it's working for 1.8.2 now, and I've been using the 32e5 on the [Piranha Synth](http://mrp3.com/sftsynth.html) I'm closing this issue.
